workflows:
  ios-native:
    name: iOS Native Build
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 18.20.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: yarn install --frozen-lockfile || npm install
      - name: Install CocoaPods dependencies
        script: cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/RemoveHelp.xcworkspace \
            -scheme RemoveHelp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/RemoveHelp.xcarchive \
            clean archive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/RemoveHelp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios
    artifacts:
      - $CM_BUILD_DIR/build/ios/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APP_STORE_CONNECT_APPLE_ID
        api_key: $APP_STORE_CONNECT_API_KEY
        api_issuer: $APP_STORE_CONNECT_API_ISSUER_ID
        team_id: $APP_STORE_CONNECT_TEAM_ID 