workflows:
  ios-eas-build:
    name: iOS EAS Build
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 18.20.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: yarn install --frozen-lockfile || npm install
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: EAS Build iOS
        script: |
          eas build --platform ios --profile production --non-interactive --auto-submit
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.ipa
      - build/**/outputs/**/*.app
      - build/**/outputs/**/*.xcarchive
      - build/**/outputs/**/*.dSYM.zip
    publishing:
      email:
        recipients:
          - your-email@example.com 